---
all:
  children:
    cisco_cml:
      hosts:
        cml_host:
          ansible_host: 10.10.20.161
          ansible_user: developer
          ansible_password: C1sco12345
    cisco_nxos:
      hosts:
        sw01-nxos:
          ansible_host: 10.10.20.177
          ansible_user: admin
          ansible_password: admin
          ansible_connection: network_cli
          ansible_network_os: nxos
        sw02-nxos:
          ansible_host: 10.10.20.178
          ansible_user: admin
          ansible_password: admin
          ansible_connection: network_cli
          ansible_network_os: nxos
